name: birdie-os
description: Bazzite for me
alt-tags:
  - testing

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: testing

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "curl -o /tmp/ProtonMail-desktop-beta.rpm https://proton.me/download/mail/linux/ProtonMail-desktop-beta.rpm"
      - "rpm-ostree install /tmp/ProtonMail-desktop-beta.rpm"

  - type: rpm-ostree
    install:
      - zsh
      - code
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - pv
      - bsdtar
      - xorriso
      - syslinux
      - mtools

  - type: script
    snippets:
      - "sysctl -p"
      - "sed -i '/^PRETTY_NAME/s/Bazzite/Birdie/' /usr/lib/os-release"
      - "sed -i 's/bazzite_logo.svgz/birdie_logo.svgz/g' /usr/share/plasma/look-and-feel/com.valve.vapor.desktop/contents/splash/Splash.qml"
      - "sed -i 's/bazzite_logo.svgz/birdie_logo.svgz/g' /usr/share/plasma/look-and-feel/com.valve.vgui.desktop/contents/splash/Splash.qml"
      - "sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/vscode.repo"
      - "sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/docker-ce.repo"
    scripts:
      - image-info.sh
      - google-chrome-install.sh
      - install_dracula.sh

  - type: systemd
    user:
      enabled:
        - birdie-user-setup
    system:
      enabled:
        - birdie-system-setup
        - docker.socket
        - libvirtd
      disabled:
        - podman.socket

  - type: default-flatpaks
    notify: true
    user:
      install:
        - com.discordapp.Discord
      remove:
        - org.mozilla.firefox

  - type: signing
