name: birdie-os
description: Bazzite for developers

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - alacritty
      - virt-manager
      - virt-viewer
      - edk2-ovmf
      - libvirt
      - qemu
      - qemu-char-spice
      - qemu-device-display-virtio-gpu
      - qemu-device-display-virtio-vga
      - qemu-device-usb-redirect
      - qemu-img
      - qemu-system-x86-core
      - qemu-user-binfmt
      - qemu-user-static
      - code
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
      - papirus-icon-theme      
      - pv
      - bsdtar
      - xorriso
      - syslinux
      - mtools
    remove:
      - ptyxis

  - type: script
    snippets:
      - "sysctl -p"
      - "sed -i '/^PRETTY_NAME/s/Bazzite/Birdie/' /usr/lib/os-release"
      - "sed -i 's/bazzite_logo.svgz/birdie_logo.svgz/g' /usr/share/plasma/look-and-feel/com.valve.vapor.desktop/contents/splash/Splash.qml"
      - "sed -i 's/bazzite_logo.svgz/birdie_logo.svgz/g' /usr/share/plasma/look-and-feel/com.valve.vgui.desktop/contents/splash/Splash.qml"
      - "sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/vscode.repo"
      - "sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/docker-ce.repo"      
    scripts:
      - image-info.sh
      - google-chrome-install.sh         

  - type: systemd
    user:
      enabled:
        - birdie-user-setup
    system:
      enabled:
        - birdie-system-setup
        - docker.socket
        - libvirtd        
      disabled:
        - podman.socket

  - type: default-flatpaks
    notify: true
    user:
      install:
        - org.inkscape.Inkscape
        - org.videolan.VLC
        - com.discordapp.Discord
        - one.ablaze.floorp
      remove:
        - org.mozilla.firefox

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing
